Migrating:
CREATE TABLE "leaderboard"("id" INTEGER PRIMARY KEY,"name" VARCHAR NOT NULL,"s_easy" INTEGER NOT NULL,"s_medium" INTEGER NOT NULL,"s_hard" INTEGER NOT NULL)
Migrating:
CREATE TABLE "c_pool"("id" INTEGER PRIMARY KEY,"from" INTEGER NOT NULL,"to" INTEGER NOT NULL,"target" INTEGER NOT NULL)